package app;

import models.Location;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import utils.AccurateDistanceCalculator;

/**
 * Singleton service representing the real-world road graph.
 * It loads the predefined nodes and edges from the CSV files generated by MapDataFetcher.
 */
public class CityMap {

    private static CityMap instance;

    // Node ID -> Location
    private final Map<String, Location> nodes = new HashMap<>();
    
    // Adjacency List: Node ID -> List of Edge(NeighborId, travelTimeSeconds)
    private final Map<String, List<Edge>> adjacencyList = new HashMap<>();

    private double minLat = Double.MAX_VALUE;
    private double maxLat = -Double.MAX_VALUE;
    private double minLon = Double.MAX_VALUE;
    private double maxLon = -Double.MAX_VALUE;

    public static class Edge {
        public final String targetNode;
        public final double travelTimeSeconds;

        public Edge(String targetNode, double travelTimeSeconds) {
            this.targetNode = targetNode;
            this.travelTimeSeconds = travelTimeSeconds;
        }
    }

    private CityMap() {
        loadGraph();
    }

    public static synchronized CityMap getInstance() {
        if (instance == null) {
            instance = new CityMap();
        }
        return instance;
    }

    private void loadGraph() {
        try {
            // Load Nodes
            BufferedReader nodeReader = new BufferedReader(new FileReader("map_nodes.csv"));
            String line;
            while ((line = nodeReader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length == 3) {
                    double lat = Double.parseDouble(parts[1]);
                    double lon = Double.parseDouble(parts[2]);
                    nodes.put(parts[0], new Location(lat, lon));
                    adjacencyList.put(parts[0], new ArrayList<>());
                    
                    if (lat < minLat) minLat = lat;
                    if (lat > maxLat) maxLat = lat;
                    if (lon < minLon) minLon = lon;
                    if (lon > maxLon) maxLon = lon;
                }
            }
            nodeReader.close();

            // Load Edges
            BufferedReader edgeReader = new BufferedReader(new FileReader("map_edges.csv"));
            while ((line = edgeReader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length == 3) {
                    String u = parts[0];
                    String v = parts[1];
                    double dist = Double.parseDouble(parts[2]);
                    if (adjacencyList.containsKey(u)) {
                        adjacencyList.get(u).add(new Edge(v, dist));
                    }
                }
            }
            edgeReader.close();

            System.out.println("[CityMap] Loaded " + nodes.size() + " intersections and road networks.");

        } catch (IOException e) {
            System.err.println("[CityMap] Error loading map files! Please ensure MapDataFetcher has run first. " + e.getMessage());
        }
    }

    public Map<String, Location> getNodes() {
        return nodes;
    }

    public Map<String, List<Edge>> getAdjacencyList() {
        return adjacencyList;
    }

    public double getMinLat() { return minLat; }
    public double getMaxLat() { return maxLat; }
    public double getMinLon() { return minLon; }
    public double getMaxLon() { return maxLon; }

    /**
     * "Snaps" an arbitrary coordinate to the nearest valid intersection (Node) in the graph.
     */
    public String snapToNearestNode(Location target) {
        String nearestId = null;
        double minDistance = Double.MAX_VALUE;

        for (Map.Entry<String, Location> entry : nodes.entrySet()) {
            double dist = AccurateDistanceCalculator.calculateDistance(target, entry.getValue());
            if (dist < minDistance) {
                minDistance = dist;
                nearestId = entry.getKey();
            }
        }
        return nearestId;
    }
}
